### ISSUE TITLE
Chrome can't install extension

### ISSUE THREAD

**Issue by benwerd** [mapkyca/KnownChrome#2]
On my system, the plugin generates a .zip. Unfortunately, Chrome refuses to install it on my system (OS X Yosemite), declaring that the archive is invalid.

It may want a .crx archive. There's a guide to building one here:

http://stackoverflow.com/questions/5013263/create-google-chrome-crx-file-with-php

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownChrome/issues/2" class="u-in-reply-to"></a>Hmmmph...

Is the zip itself valid (i.e. you can open it with whatever it is apples use to read archives)?

Will look into the crx (good for a number of reasons)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownChrome/issues/2" class="u-in-reply-to"></a>Ok, give the latest version a crack... now generates a CRX file.

**Comment by benwerd** [comment]
Works beautifully!

**Comment by rmdes** [comment]
<a href="https://github.com/mapkyca/KnownChrome/issues/2" class="u-in-reply-to"></a>Does not work on Dreamhost Shared hosting. ask about a Phar extension ?
ends up on a white page /yourdomain/chrome/download
no problem getting the CRX on a test site on a VPS instance. 

![screenshot_185](https://cloud.githubusercontent.com/assets/12155003/14941639/a4497f3a-0fa2-11e6-81d4-e188ea607a19.png)

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownChrome/issues/2" class="u-in-reply-to"></a>Looks like you're missing the extension...

**Comment by rmdes** [comment]
But isn't it also everyone using or trying to use knownChrome from shared
hosting such Dreamhost?

No way to install the Phar extension from what I know at Dreamhost..

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/KnownChrome/issues/2#issuecomment-217154730" class="u-in-reply-to"></a>Phar should be installed for PHP > 5.3, but I suspect the shared hosts are disabling it in config.

Perhaps this is something you can enable on your host?

**Comment by rmdes** [comment]
I will contact Dreamhost and see what they say...after all they were doing a
promo to use Known and their shared hosting..  

I have 2 accounts at dreamhost and both of them fail at having Phar installed.

thanks for your reply, i'll report what they say here.

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/KnownChrome/issues/2#issuecomment-217958425" class="u-in-reply-to"></a>Well, the Chrome extension isn't "official" Known, so I'll give them some slack ;)

I'll be interested in what they say, and their reasons (I suspect they just blanket disable extensions that are not commonly used for security reasons), meanwhile I'll see if I can find an alternative/workaround.

**Comment by rmdes** [comment]
Just confirmed with Dreamhost, it's easy to fix 
just add extension=phar.so into /home/username/.php/5.6/phprc
or the consequent PHP version currently in use.

**Comment by rmdes** [comment]
is it intended that after publishing a new post with the Chrome extension the extension refresh to this view ? 
![screenshot_199](https://cloud.githubusercontent.com/assets/12155003/15173761/4d8118de-175e-11e6-8aff-942b575b4dc7.png)

wouldn't be more logical to have a notification sayin it got successfully posted or something else than loading the whole website in "mobile" mode ?

**Comment by mapkyca** [comment]
Probably... 

It follows the same flow as the firefox endpoint, so this is probably something for upstream Known.
