### ISSUE TITLE
Could not generate keypair

### ISSUE THREAD

**Issue by davesgonechina** [mapkyca/KnownChrome#5]
When I click to download the extension, I get a blank page. Returning to the administration page, I get a "Could not generate keypair" error.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownChrome/issues/5" class="u-in-reply-to"></a>That means that OpenSSL was unable to export you PEM, which points to the OpenSSL module being installed (hence why it tried to generate a .CRX) but misconfigured somewhere.

The installation notes point to needing a correctly configured openssl.cnf: http://php.net/manual/en/function.openssl-pkey-export.php

**Comment by davesgonechina** [comment]
Well spotted, turns out my docker container didn't have openssl installed, now it works. Thanks!
